name: docker-publish

on:
  release:
    type: [published]
  push:
    branches: [ci]

env:
  REGISTRY: ghcr.io
  REPOSITORY: normal-dockerfile
  TAG: ${{ github.ref_name }}

jobs:
  ghcr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        if: env.SKIP_CI != 'true'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: env.SKIP_CI != 'true'
        with:
          driver-opts: image=moby/buildkit:buildx-stable-1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        if: env.SKIP_CI != 'true'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache Maven Repos
        if: env.SKIP_CI != 'true'
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-java@v1
        if: env.SKIP_CI != 'true'
        with:
          java-version: 8
      - name: Build with Maven
        if: env.SKIP_CI != 'true'
        run: mvn -B install -Dmaven.javadoc.skip=true -B -Drat.skip=true -Djacoco.skip=true -DskipITs -DskipTests -f ./normal-dockerfile/pom.xml
      - name: Build and Push to DockerHub / ghcr.io
        uses: docker/build-push-action@v3
        if: env.SKIP_CI != 'true'
        with:
          context: ./normal-dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/skyleaworlder/${{ env.REPOSITORY }}:${{ env.TAG }}
            ${{ env.REGISTRY }}/skyleaworlder/${{ env.REPOSITORY }}:latest

  dockerhub:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        if: env.SKIP_CI != 'true'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: env.SKIP_CI != 'true'
        with:
          driver-opts: image=moby/buildkit:buildx-stable-1
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_PASSWORD }}
      - name: Cache Maven Repos
        if: env.SKIP_CI != 'true'
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-java@v1
        if: env.SKIP_CI != 'true'
        with:
          java-version: 8
      - name: Build with Maven
        if: env.SKIP_CI != 'true'
        run: mvn -B install -Dmaven.javadoc.skip=true -B -Drat.skip=true -Djacoco.skip=true -DskipITs -DskipTests -f ./normal-dockerfile/pom.xml
      - name: Build and Push to DockerHub / ghcr.io
        uses: docker/build-push-action@v3
        if: env.SKIP_CI != 'true'
        with:
          context: ./normal-dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            skyleaworlder/${{ env.REPOSITORY }}:${{ env.TAG }}
            skyleaworlder/${{ env.REPOSITORY }}:latest